<a href="https://colab.research.google.com/github/Ericatuitui/MSSP607/blob/main/WeeklyModules/Week05/Participation_5_Huarui_Yao.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
from google.colab import userdata
import os
github_token = userdata.get('Git_Key')
owner = 'Ericatuitui'
repository = 'MSSP607'
clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'
!git clone {clone_url}

fatal: destination path 'MSSP607' already exists and is not an empty directory.

In [25]:
import pandas as pd

aapl = pd.read_csv('/content/MSSP607/data/aapl.csv')
amzn = pd.read_csv('/content/MSSP607/data/amzn.csv')
nflx = pd.read_csv('/content/MSSP607/data/nflx.csv')
fb = pd.read_csv('/content/MSSP607/data/fb.csv')
goog = pd.read_csv('/content/MSSP607/data/goog.csv')

In [26]:
aapl['ticker'] = 'AAPL'
amzn['ticker'] = 'AMZN'
nflx['ticker'] = 'NFLX'
fb['ticker'] = 'FB'
goog['ticker'] = 'GOOG'

In [27]:
df = pd.concat([aapl, amzn, nflx, fb, goog])

In [28]:
df.to_csv('/content/MSSP607/WeeklyModules/Week05/faanf.csv', index=False)

In [29]:
df = pd.read_csv('/content/MSSP607/WeeklyModules/Week05/faanf.csv')

df['date'] = pd.to_datetime(df['date'])
df['volume'] = df['volume'].astype(int)

In [30]:
df = df.sort_values(['date', 'ticker'])

In [31]:
df.nlargest(7, 'volume')

          date      open      high       low     close     volume ticker
895 2018-07-26  174.8900  180.1300  173.7500  176.2600  169803668     FB
806 2018-03-20  167.4700  170.2000  161.9500  168.1500  129851768     FB
810 2018-03-26  160.8200  161.1000  149.0200  160.0600  126116634     FB
807 2018-03-21  164.8000  173.4000  163.3000  169.3900  106598834     FB
182 2018-09-21  219.0727  219.6482  215.6097  215.9768   96246748   AAPL
245 2018-12-21  156.1901  157.4845  148.9909  150.0862   95744384   AAPL
212 2018-11-02  207.9295  211.9978  203.8414  205.8755   91328654   AAPL

In [32]:
melted_df = df.melt(id_vars=['date', 'ticker'])

In [33]:
melted_df.head()

        date ticker variable      value
0 2018-01-02   AAPL     open   166.9271
1 2018-01-02   AMZN     open  1172.0000
2 2018-01-02     FB     open   177.6800
3 2018-01-02   GOOG     open  1048.3400
4 2018-01-02   NFLX     open   196.1000