<a href="https://colab.research.google.com/github/Ericatuitui/MSSP607/blob/main/WeeklyModules/Week04/Participation_week_4_Huarui_Yao_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
from google.colab import userdata
import os
github_token = userdata.get('Git_Key')
owner = 'Ericatuitui'
repository = 'MSSP607'
clone_url = f'https://{github_token}@github.com/{owner}/{repository}.git'
!git clone {clone_url}

fatal: destination path 'MSSP607' already exists and is not an empty directory.

In [11]:
import pandas as pd
parsed = pd.read_csv('/content/MSSP607/WeeklyModules/Week04/parsed.csv')

In [12]:
parsed.columns
Japandata=parsed[parsed["parsed_place"]=="Japan"]
Japanmb=Japandata[Japandata["magType"] == "mb"]
Japanmag=Japanmb["mag"]
Japanmag.quantile(0.95)

np.float64(4.9)

In [13]:
Indonesiadata=parsed[parsed["parsed_place"]=="Indonesia"]
parsed["type"].unique()
Indonesiaeq=Indonesiadata[Indonesiadata["type"] == "earthquake"]
Indonesiaeqn=len(Indonesiaeq)
Indonesiaeq["tsunami"].unique()
Indonesiaeqt=Indonesiaeq[Indonesiaeq["tsunami"] == 1]
Indonesiaeqtn=len(Indonesiaeqt)
print((Indonesiaeqtn/Indonesiaeqn)*100)

23.12925170068027

In [14]:
Nevadadata = parsed[parsed["parsed_place"] == "Nevada"]
Nevadadata.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

In [15]:
ring_of_fire = ["Bolivia", "Chile", "Ecuador", "Peru", "Costa Rica", "Guatemala", "Mexico", "Japan", "Philippines", "Indonesia", "New Zealand", "Antarctica", "Canada", "Fiji", "Alaska", "Washington", "California","Russia", "Taiwan", "Tonga", "Kermadec Islands" ]
parsed["newringoffire"] = parsed["parsed_place"].isin(ring_of_fire)
parsed["newringoffire"] = (parsed["parsed_place"].isin(ring_of_fire) | parsed["parsed_place"].str.contains("Antarctic"))
parsed.loc[parsed['parsed_place'] == 'New Mexico','ring_of_fire'] = False

In [16]:
parsed["newringoffire"].value_counts()

newringoffire
True     7188
False    2144
Name: count, dtype: int64

In [17]:
parsed.loc[parsed['newringoffire'], "tsunami"].sum()

np.int64(45)